apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: task-platform-backend
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - task-platform

  selector:
    matchLabels:
      app: backend

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s